# Generated by Django 5.0.6 on 2024-05-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviços', '0002_alter_servico_protocolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='identificador',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
