# Generated by Django 5.0.4 on 2024-05-01 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Livros',
            new_name='Livro',
        ),
    ]
