# Generated by Django 5.0.4 on 2024-05-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0002_rename_livros_livro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=30)),
                ('co_autor', models.CharField(blank=True, max_length=30)),
                ('data_casdatro', models.DateField()),
                ('emprestado', models.BooleanField(default=False)),
                ('nome_emprestado', models.CharField(blank=True, max_length=30)),
                ('data_emprestimo', models.DateTimeField(blank=True)),
                ('data_devolucao', models.DateTimeField(blank=True)),
                ('tempo_duracao', models.DateField(blank=True)),
            ],
            options={
                'verbose_name': 'Livro',
            },
        ),
        migrations.DeleteModel(
            name='Livro',
        ),
    ]
