# Generated by Django 5.0.4 on 2024-05-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0003_livros_delete_livro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='data_casdatro',
            field=models.DateField(auto_now=True),
        ),
    ]
