# Generated by Django 5.0.4 on 2024-05-01 18:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0006_alter_livros_co_autor_alter_livros_data_casdatro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='data_casdatro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
