# Generated by Django 5.0.4 on 2024-05-02 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0009_livros_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livros',
            old_name='data_casdatro',
            new_name='data_cadastro',
        ),
    ]
