# Generated by Django 5.0.4 on 2024-05-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0015_alter_emprestimo_data_devolucao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='tempo_duracao',
        ),
    ]
