'''
Bibliotecas Usadas:
    Pygame
    Time
    Keyboard
    Colorama
'''
import os, colorama, pygame, time, keyboard
pygame.mixer.init()
from colorama import Fore, Back, Style
colorama.init(autoreset=True)
from pygame import mixer
os.system('cls')
import sys,time

#Configurações de operação
def sprint(str):
   for c in str + '\n':
     sys.stdout.write(c)
     sys.stdout.flush()
     time.sleep(4./90)

def ssprint(str):
   for c in str + '\n':
     sys.stdout.write(c)
     sys.stdout.flush()
     time.sleep(6./90)

def editNome():
    os.system('cls')
    sprint(f'Então o seu nome é {"".join(User)}, correto?')
    name_choice = input('[1] SIM\n[2] NÃO\n>>> ')
    if name_choice == '2':
        newname = input('Corrija seu nome, por favor\n>>> ')
        User[0] = newname
        editNome()
    else:
        sprint('Ótimo.')
        input()

def editSigno():
    os.system('cls')
    print(Fore.RED + 'ANFITRIÃO')
    sprint(f'Então seu signo é {"".join(Signo)}, correto?')
    sign_choice = input('[1] SIM\n[2] NÃO\n>>> ')
    if sign_choice == '2':
        print(Fore.RED + 'ANFITRIÃO')
        sprint('Claro, podemos corrigir.')
        newsign = input('Informe seu signo correto:\n>>> ')
        Signo[0] = newsign
        editSigno()
    else:
        sprint('Perfeito.')
        input()
        os.system('cls')

def cleanup():
    EscolhaImpacto1.clear
    EscolhaImpacto2.clear
    EscolhaImpacto3.clear
    EscolhaQueimarArvore.clear
    EscolhaCriançaSalva.clear
    QTE_Tutorial.clear
    QTE_1.clear
    QTE_2.clear
    QTE_3.clear
    QTE_4.clear
    QTE_5.clear
    QTE_6.clear

def menu():
    while True:
        os.system('cls')
        #No caso de erro ao encontrar música, procurar localização na pasta que contém a música nos arquivos do jogo e alterar sua localização no código abaixo.
        '''pygame.mixer.music.load("menu\music\menu_song.ogg")
        pygame.mixer.music.set_volume(0.2)
        pygame.mixer.music.play()'''
        print(Style.BRIGHT + Fore.RED + Back.LIGHTWHITE_EX + '----- THE GUTTER -----')
        sprint('[1] Iniciar aventura (DEMO)')
        sprint('[0] Sair')
        menu_choice = input('>>> ')
        if menu_choice == '1':
            pygame.mixer.music.fadeout(1000)
            introAnfitrião()
            inicio_demo()
        elif menu_choice == '0':
            print('Nos vemos em breve...')
            break

def new_menu():
    while True:
        os.system('cls')
        #No caso de erro ao encontrar música, procurar localização na pasta que contém a música nos arquivos do jogo e alterar sua localização no código abaixo.
        '''pygame.mixer.music.load("menu\music\menu_song.ogg")
        pygame.mixer.music.set_volume(0.2)
        pygame.mixer.music.play()'''
        print(Style.BRIGHT + Fore.RED + Back.LIGHTWHITE_EX + '----- THE GUTTER -----')
        sprint('[1] Iniciar aventura (DEMO)')
        sprint('[2] Escolhas')
        sprint('[0] Sair')
        menu_choice = input('>>> ')
        if menu_choice == '1':
            pygame.mixer.music.fadeout(1000)
            introAnfitrião()
            inicio_demo()
        elif menu_choice == '2':
            show_choices()
        elif menu_choice == '0':
            print('Nos vemos em breve...')
            break

def show_choices():
    os.system('cls')
    print(Fore.RED + Back.WHITE + '===== ESCOLHAS =====')
    print('')
    print('========================================================================')
    sprint(f'{EscolhaImpacto1}')
    print('========================================================================')
    sprint(f'{EscolhaImpacto2}')
    print('========================================================================')
    sprint(f'{EscolhaImpacto3}')
    print('========================================================================')
    sprint(f'{EscolhaQueimarArvore}')
    print('========================================================================')
    sprint(f'{EscolhaCriançaSalva}')
    print('========================================================================')
    input('[ENTER] para continuar...')

#Dados de jogo importantes
User = []
Signo = []
Planta = []
Inventario = []

#Escolhas
EscolhaImpacto1 = []
EscolhaImpacto2 = []
EscolhaImpacto3 = []
EscolhaQueimarArvore = []
EscolhaCriançaSalva = []

#QTE's

QTE_Tutorial = []
QTE_1 = []
QTE_2 = []
QTE_3 = []
QTE_4 = []
QTE_5 = []
QTE_6 = []

def qte_tutorial():
    print("Pressione a tecla 'A'!")
    time.sleep(2)  # Aguarda 2 segundos antes de começar

    start_time = time.time()  # Registra o tempo inicial

    while True:
        if keyboard.is_pressed('a'):  # Verifica se a tecla 'A' foi pressionada
            end_time = time.time()  # Registra o tempo em que a tecla foi pressionada
            reaction_time = end_time - start_time  # Calcula o tempo de reação
            if reaction_time < 2:
                print('SUCESSO!')
                QTE_Tutorial.append('SUCESSO')
            else:
                print('FALHA!')
                QTE_Tutorial.append('FALHA')
            print("Tempo de reação:", reaction_time)
            break  # Sai do loop
def qte_1():
    print("Pressione a tecla 'L'!")
    time.sleep(2)

    start_time = time.time() 

    while True:
        if keyboard.is_pressed('l'):
            end_time = time.time() 
            reaction_time = end_time - start_time 
            if reaction_time < 3:
                print('SUCESSO!')
                QTE_1.append('SUCESSO')
            else:
                print('FALHA!')
                QTE_1.append('FALHA')
            print("Tempo de reação:", reaction_time)
            break
def qte_2():
    print("Pressione a tecla 'e'!")
    time.sleep(2)

    start_time = time.time() 

    while True:
        if keyboard.is_pressed('e'):
            end_time = time.time() 
            reaction_time = end_time - start_time 
            if reaction_time < 2:
                print('SUCESSO!')
                QTE_2.append('SUCESSO')
            else:
                print('FALHA!')
                QTE_2.append('FALHA')
            print("Tempo de reação:", reaction_time)
            break
def qte_3():
    print("Pressione a tecla 'r'!")
    time.sleep(2)

    start_time = time.time() 

    while True:
        if keyboard.is_pressed('r'):
            end_time = time.time() 
            reaction_time = end_time - start_time 
            if reaction_time < 2:
                print('SUCESSO!')
                QTE_3.append('SUCESSO')
            else:
                print('FALHA!')
                QTE_3.append('FALHA')
            print("Tempo de reação:", reaction_time)
            break
def qte_4():
    print("Pressione a tecla 'J'!")
    time.sleep(2)

    start_time = time.time() 

    while True:
        if keyboard.is_pressed('j'):
            end_time = time.time() 
            reaction_time = end_time - start_time 
            if reaction_time < 1:
                print('SUCESSO!')
                QTE_4.append('SUCESSO')
            else:
                print('FALHA!')
                QTE_4.append('FALHA')
            print("Tempo de reação:", reaction_time)
            break
def qte_5():
    print("Pressione a tecla 'P'!")
    time.sleep(2)

    start_time = time.time() 

    while True:
        if keyboard.is_pressed('p'):
            end_time = time.time() 
            reaction_time = end_time - start_time 
            if reaction_time < 1:
                print('SUCESSO!')
                QTE_5.append('SUCESSO')
            else:
                print('FALHA!')
                QTE_5.append('FALHA')
            print("Tempo de reação:", reaction_time)
            break
def qte_6():
    print("Pressione a tecla 'G'!")
    time.sleep(2)

    start_time = time.time() 

    while True:
        if keyboard.is_pressed('g'):
            end_time = time.time() 
            reaction_time = end_time - start_time 
            if reaction_time < 1:
                print('SUCESSO!')
                QTE_6.append('SUCESSO')
            else:
                print('FALHA!')
                QTE_6.append('FALHA')
            print("Tempo de reação:", reaction_time)
            break

#Cenários

def introAnfitrião():
    os.system('cls')
    sprint('Olá, é um prazer ter você conosco.')
    print(Back.LIGHTBLACK_EX + 'PRESSIONE ENTER PARA CONTINUAR...')
    input()
    os.system('cls')
    sprint('Gostaria de ser formal. Qual o seu nome?')
    name = input('>>> ')
    User.append(name)
    editNome()
    sprint(f'É um prazer lhe conhecer, {"".join(User)}.')
    input()
    os.system('cls')
    print(Fore.RED + 'ANFITRIÃO')
    sprint('Pode me chamar de Anfitrião. Serei responsável por guiar você nessa jornada.')
    sprint('Mas antes de tudo, gostaria de dar alguns avisos.')
    input()
    os.system('cls')
    print(Fore.RED + 'ANFITRIÃO')
    sprint('Gostaria de saber qual o seu signo. É importante, para o futuro do seu jogo, claro.')
    sign = input('>>> ')
    Signo.append(sign)
    editSigno()
    if sign.lower() == 'áries' or sign.lower() == 'aries':
        print(Fore.RED +'ANFITRIÃO')
        sprint('Ah, sim. Áries, signo da força.\nEspero que tal força o guie em sua jornada.')
        Signo.append('Áries')
        Planta.append('Ira de Xandoré')
    elif sign.lower() == 'touro':
        print(Fore.RED +'ANFITRIÃO')
        sprint('Ah, sim. Touro, signo da determinação e perseverança.\nEspero que tal resiliência o guie em sua jornada.')
        Signo.append('Touro')
        Planta.append('Hâdia de Rudá')
    elif sign.lower() == 'gêmeos' or sign.lower() == 'gemeos':
        print(Fore.RED +'ANFITRIÃO')
        sprint('Ah, sim. Gêmeos, signo da inteligência.\nEspero que tal curiosidade o guie em sua jornada.')
        Signo.append('Gêmeos')
        Planta.append('Awôto de Polô')
    elif sign.lower() == 'câncer' or sign.lower() == 'cancer':
        print(Fore.RED +'ANFITRIÃO')
        sprint('Ah, sim. Câncer, signo do afeto.\nEspero que tal caridade o guie em sua jornada.')
        Signo.append('Câncer')
        Planta.append('Áuéra de Jaci')
    elif sign.lower() == 'leão' or sign.lower() == 'leao':
        print(Fore.RED +'ANFITRIÃO')
        sprint('Ah, sim. Leão, signo do magnetismo.\nEspero que tal auto-confiança o guie em sua jornada.')
        Signo.append('Leão')
        Planta.append('Alâdia de Guaraci')
    elif sign.lower() == 'virgem':
        print(Fore.RED +'ANFITRIÃO')
        sprint('Ah, sim. Virgem, signo da sabedoria.\nEspero que tal estratégia o guie em sua jornada.')
        Signo.append('Virgem')
        Planta.append('Ewûa de Sumé')
    elif sign.lower() == 'libra':
        print(Fore.RED +'ANFITRIÃO')
        sprint('Ah, sim. Libra, signo da diplomacia.\nEspero que tal empatia o guie em sua jornada.')
        Signo.append('Libra')
        Planta.append('Inkã de Jurupari')
    elif sign.lower() == 'escorpião' or sign.lower() == 'escorpiao':
        print(Fore.RED +'ANFITRIÃO')
        sprint('Ah, sim. Escorpião, signo da intensidade.\nEspero que tal realismo o guie em sua jornada.')
        Signo.append('Escorpião')
        Planta.append('Anhangá')
    elif sign.lower() == 'sagitário' or sign.lower() == 'sagitario':
        print(Fore.RED +'ANFITRIÃO')
        sprint('Ah, sim. Sagitário, signo do otimismo.\nEspero que tal paixão o guie em sua jornada.')
        Signo.append('Sagitário')
        Planta.append('Mangará de Tupã')
    elif sign.lower() == 'capricornio':
        print(Fore.RED +'ANFITRIÃO')
        sprint('Ah, sim. Capricornio, signo da disciplina.\nEspero que tal diligência o guie em sua jornada.')
        Signo.append('Capricornio')
        Planta.append('Fogo de Angra')
    elif sign.lower() == 'aquário' or sign.lower() == 'aquario':
        print(Fore.RED +'ANFITRIÃO')
        sprint('Ah, sim. Aquário, signo da ambição.\nEspero que tal esforço o guie em sua jornada.')
        Signo.append('Aquário')
        Planta.append('Flauta de Akuanbuba')
    elif sign.lower() == 'peixes':
        print(Fore.RED +'ANFITRIÃO')
        sprint('Ah, sim. Peixes, signo da fluidez.\nEspero que tal imaginação o guie em sua jornada.')
        Signo.append('Peixes')
        Planta.append('Rio de Caramuru')
    input('')
    os.system('cls')
    print(Fore.RED + 'ANFITRIÃO')
    sprint('Espero que você tenha consciência do quê está fazendo.')
    answer_menu = input('[1] SIM\n[2] NÃO\n>>> ')[0]
    if answer_menu == '1' or answer_menu.lower() == 's':
        os.system('cls')
        print(Fore.RED + 'ANFITRIÃO')
        sprint('Ah, é ótimo saber disso. Me deixa mais tranquilo saber que cuidará deles.')
        sprint('Creio então que não haja necessidade de explicar o que está fazendo, então podemos prosseguir.')
        answer_menu2 = input('[1] "Não, por favor, me explique!\n[2] "Sim, podemos prosseguir\n>>> ')
        if answer_menu2 == '1':
            os.system('cls')
            print(Fore.RED + 'ANFITRIÃO')
            sprint('Que infortúno. Deveria ter dito que não sabia o que estamos fazendo aqui.\nMas tudo bem.')
            sprint('Estamos brincando com a vida.\nVocê receberá em suas mãos, o controle das decisões de Lara, uma jovem em uma missão.')
            input()
            sprint('Me sinto mal em estragar a suspresa, então espero que se divirta e a conheça melhor.') 
            input()
            sprint('ou não.')
            input()
            sprint('Não sou seu mestre, apenas seu guia.')
            input()
            sprint('Não cabe a mim cuidar de tais intempérios.') 
            input()
            os.system('cls')
            print(Fore.RED + 'ANFITRIÃO')
            print(Fore.RED + 'Essa é sua missão.')
            input()
            os.system('cls')
            print(Fore.RED + 'ANFITRIÃO')
            sprint('No mais, espero que se divirta.')
            input()
            os.system('cls')
            ssprint('Bom jogo...')
            input()
        if answer_menu2 == '2':
            print(Fore.RED + 'ANFITRIÃO')
            sprint('Perfeito!')
            input()
            os.system('cls')
            ssprint('Bom jogo...')
            input()
    elif answer_menu == '2' or answer_menu.lower() == 'n':
        os.system('cls')
        print(Fore.RED + 'ANFITRIÃO')
        sprint('...Não? É uma pena. Não para você, claro. Tenho certeza que irá se divertir tremendamente com a aventura.\n Mas não cabe a você se preocupar com isso.')
        input()
        sprint('Estamos brincando com a vida.\nVocê receberá em suas mãos, o controle das decisões de Lara, uma jovem em uma missão.')
        input()
        sprint('Me sinto mal em estragar a suspresa, então espero que se divirta e a conheça melhor.') 
        input()
        sprint('ou não.')
        input()
        sprint('Não sou seu mestre, apenas seu guia.')
        input()
        sprint('Não cabe a mim cuidar de tais intempérios.') 
        input()
        os.system('cls')
        print(Fore.RED + 'ANFITRIÃO')
        print(Fore.RED + 'Essa é sua missão.')
        input()
        os.system('cls')
        print(Fore.RED + 'ANFITRIÃO')
        sprint('No mais, espero que se divirta.')
        input()
        os.system('cls')
        ssprint('Bom jogo...')
        input()

def inicio_demo():
    os.system('cls')
    sprint('Exatamente como o pajê havia dito.\nPodre, escura, morta e rodeada de escuridão, a árvore se estendia ao longo, em direção aos céus, porém morta.')
    sprint('Nenhuma folha que representasse vida, nenhuma cor que representasse seiva. Apenas morte.') 
    input('')
    sprint('Respirei profundamente, sentindo o ar úmido e pesado dos pântanos preenchendo meus pulmões, enquanto o zunir dos insetos assombra meus ouvidos.')
    input('')
    os.system('cls')
    print(Fore.YELLOW + 'LARA')
    sprint("Calma, respira. É simples. Entrar, pegar a droga do livro e sair. Sem complicação.")
    input('')
    os.system('cls')
    sprint('Sem complicações...')
    input('')
    sprint('Minhas mãos tremiam e a minhas pernas bambeavam.')
    sprint('Eu não conseguia sentir forças para me mover, como se a terra lodosa me chamasse para desistir.\nTalvez o ar, talvez a lama funda, talvez o medo que possuia cada vez mais me fizesse sentir mais medo do que eu devia.')
    input('')
    sprint('Afinal, ele havia dito que era época de caça. Ela não estaria em casa. Vai ficar tudo bem.')
    input('')
    os.system('cls')
    sprint('Respirei fundo mais algumas vezes e me prostei em direção ao buraco na casca rude da árvore.\nQuanto mais perto me aproximava, mais escuro o buraco parecia, como um portal para uma escuridão que jamais deveria ser tocada.\nFiz o sinal da cruz três vezes em meu peito, esperando que Deus pudesse me ver nesse fim de mundo.')
    input()
    os.system('cls')
    print(Fore.YELLOW +'LARA')
    sprint("Avemaria cheia de graça, senhor es convosco...")
    input('')
    os.system('cls')
    sprint('Adentrei a escuridão da árvore, entoando em minha cabeça a preçe de Nossa Senhora, atenta a todo e qualquer som que pudesse atrapalhar a calmária daquele lugar.\nO ar era umido e quieto, como se a pura presença atrapalhasse uma conversa do tempo.')
    input('')
    sprint('Andei mais alguns metros até ver uma luz ao horizonte, como uma pequena vela ao curvar de uma esquina.\nSegui em direção aquela luz o mais rápido que consegui, tentando abandonar a escuridão entre a segurança da floresta e seja lá o que estivesse a frente.')
    sprint('Ao virar a esquina, me deparei com um gigante salão, repleto de velas em todas e diversas reentrâncias que a madeira poderia permitir.')
    input('')
    os.system('cls')
    sprint('A direita, estantes corroidas por podridão e umidade, como uma leve biblioteca. A minha frente, engolfado pela escuridão que a luz não conseguia alcançar, um buraco, que exalava um calor abafado, como uma bocarra convidando para o estômago da terra.')
    print(Fore.YELLOW + 'LARA')
    sprint("Okay... Que merda eu faço agora?")
    choice1()

def choice1():
    if 'CHAVE VELHA' in Inventario and 'LAMPIÃO' in Inventario:
        direcoes_salao = input('[1] - Ir para frente\n[2] Voltar para fora\n>>> ')
        if direcoes_salao == '1':
            buraco()
        elif direcoes_salao == '2':
            choice1()        
    else:
        direcoes_salao = input('[1] - Ir para a direita\n[2] - Ir para frente\n[3] - Voltar para fora\n>>> ')
        if direcoes_salao == '1':
            os.system('cls')
            biblioteca()
        elif direcoes_salao == '2':
            os.system('cls')
            buraco()
        elif direcoes_salao == '3':
            os.system('cls')
            print(Fore.YELLOW + 'LARA')
            sprint('Não Lara, você precisa do livro. É por ela, lembra disso...')
            input('')
            os.system('cls')
            choice1()
        else:
            sprint('(Opção inválida!')
            input('')
            choice1()

def biblioteca():
    sprint(f'Segui em direção as estantes, procurando alguma pista do maldito livro que procurava. Por favor, {"".join(Planta)}, por favor...')
    input('')
    os.system('cls')
    print(Fore.YELLOW + 'LARA')
    sprint('DROGA!')
    input('')
    os.system('cls')
    sprint('A biblioteca, apesar de conter os mais diversos volumes que jamais havia ouvido falar, não parecia conter um único mísero volume que se relaciona-se a plantas.\nDiversas macabridades, mas nenhum único herbário que pudesse me guiar para uma resposta.')
    input('')
    os.system('cls')
    print(Fore.YELLOW + 'LARA')
    sprint('Por favor, esteja aqui...')
    input('')
    os.system('cls')
    sprint('Ainda nessa sala, se encontram algumas estantes com gavetas empoeiradas e um lampião.')
    direcoes_biblioteca = input('[1] - Olhar estantes\n[2] - Pegar lampião\n[3] - Voltar para o salão\n >>> ')
    if direcoes_biblioteca == '1':
        os.system('cls')
        gavetas()
    elif direcoes_biblioteca == '2':
        os.system('cls')
        lampiao()
    elif direcoes_biblioteca == '3':
        choice1()

def biblioteca_if_chave():
    os.system('cls')
    sprint('Voltei ao centro da biblioteca, observando as estantes vividas e atenta a qualquer som que pudesse me deixar alerta.')
    sprint('Apesar do estrondo, acho que eu poderia ficar um pouco mais aqui.')
    input('')
    sprint('Ainda nessa sala, se encontra um lampião')
    direcoes_biblioteca_if_chave = input('[1] - Pegar lampião\n[2] - Deixar para lá\n>>> ')
    if direcoes_biblioteca_if_chave == '1':
        os.system('cls')
        print(Fore.YELLOW + 'LARA')
        sprint('Nunca é demais.')
        input('')
        print(Style.BRIGHT + Back.WHITE + 'VOCÊ GANHOU LAMPIÃO DE LUZ!')
        Inventario.append('LAMPIÃO')
        EscolhaImpacto2.append('VOCÊ CONSEGUIU ALGO PARA ILUMINAR SEU CAMINHO!')
        input('')
        choice1()
    elif direcoes_biblioteca_if_chave == '2':
        print(Fore.YELLOW + 'LARA')
        sprint('Não, melhor não tocar em mais nada...')
        EscolhaImpacto2.append('VOCÊ NÃO LEVOU O LAMPIÃO.')
        choice1()

def biblioteca_if_lampiao():
    os.system('cls')
    sprint('Voltei ao centro da biblioteca. Talvez possa explorar um pouco mais.')
    sprint('Ainda nessa sala, se encontram as estantes com gavetas empoeiradas')
    direcoes_biblioteca_if_lampiao = input('[1] - Olhar estantes\n[2] - Deixar pra lá\n>>> ')
    if direcoes_biblioteca_if_lampiao == '1':
        sprint('Segui em direção as gavetas, que estavam acumuladas com bolor, mofo e outros fungos que prendiam as reentrâncias da gaveta.\nSeria preciso puxa-las com força para abri-las.')
        input('')
        os.system('cls')
        print(Fore.YELLOW + 'LARA')
        sprint('Talvez se eu fizer um pouco de força...')
        input('')
        sprint('Devo puxar a gaveta?')
        acao_biblioteca_chave = input('[1] - Forçar a gaveta\n[2] - Deixar para lá\n>>> ')
        if acao_biblioteca_chave == '1':
            os.system('cls')
            print(Fore.RED + 'BLAM!')
            sprint('Com um estrondo, como um velho metal se partindo, a gaveta se abriu de sobresssalto, lançando pedaços de madeira pela sala.')
            sprint('Um frio assustador subiu em meu corpo, ao sentir o silencio me engolfando novamente, como uma plateia julgando. Eu só espero que ela não esteja aqui.')
            input('')
            sprint('Depois de me recuperar do susto, notei um brilho nos restos da gaveta.\nUma chave, velha e enferrujada, presa a um cordão grudento e sujo, como se o suor tivesse se unido aos veios dos fios.')
            print(Style.BRIGHT + Back.WHITE + 'VOCÊ GANHOU CHAVE VELHA!')
            Inventario.append('CHAVE VELHA')
            EscolhaImpacto1.append('VOCÊ ABRIU A GAVETA, AVISANDO A CUCA DA SUA PRESENÇA, MAS CONSEGUINDO CHAVE VELHA.')
            choice1()
        if acao_biblioteca_chave == '2':
            os.system('cls')
            sprint('A gaveta aparenta estar fortemente barrada, e puxar poderia fazer muito barulho.')
            input('')
            os.system('cls')
            print(Fore.YELLOW + 'LARA')
            sprint('Não, eu só preciso do livro.')
            EscolhaImpacto1.append('VOCÊ NÃO ABRIU A GAVETA, DEIXANDO A CHAVE PARA TRÁS')
            choice1()
    if direcoes_biblioteca_if_lampiao == '2':
        os.system('cls')
        print(Fore.YELLOW + 'LARA')
        sprint('Não, melhor deixar pra lá.')
        input('')
        os.system('cls')
        sprint('Decidi abandonar a biblioteca, já que não havia nada mais que eu pudesse fazer aqui.')
        input('')
        choice1()

def gavetas():
    sprint('Segui em direção as gavetas, que estavam acumuladas com bolor, mofo e outros fungos que prendiam as reentrâncias da gaveta.\nSeria preciso puxa-las com força para abri-las.')
    input('')
    os.system('cls')
    print(Fore.YELLOW + 'LARA')
    sprint('Talvez se eu fizer um pouco de força...')
    input('')
    sprint('Devo puxar a gaveta?')
    acao_biblioteca_chave = input('[1] - Forçar a gaveta\n[2] - Deixar para lá\n>>> ')
    if acao_biblioteca_chave == '1':
        os.system('cls')
        print(Fore.RED + 'BLAM!')
        sprint('Com um estrondo, como um velho metal se partindo, a gaveta se abriu de sobresssalto, lançando pedaços de madeira pela sala.')
        sprint('Um frio assustador subiu em meu corpo, ao sentir o silencio me engolfando novamente, como uma plateia julgando. Eu só espero que ela não esteja aqui.')
        input('')
        sprint('Depois de me recuperar do susto, notei um brilho nos restos da gaveta.\nUma chave, velha e enferrujada, presa a um cordão grudento e sujo, como se o suor tivesse se unido aos veios dos fios.')
        print(Style.BRIGHT + Back.WHITE + 'VOCÊ GANHOU CHAVE VELHA!')
        Inventario.append('CHAVE VELHA')
        EscolhaImpacto1.append('VOCÊ ABRIU A GAVETA, AVISANDO A CUCA DA SUA PRESENÇA, MAS CONSEGUINDO CHAVE VELHA.')
        input('')
        biblioteca_if_chave()
    elif acao_biblioteca_chave == '2':
        print(Fore.YELLOW + 'LARA')
        sprint('Não...Isso não parece nem um pouco uma boa ideia.')
        sprint('Você abandona a gaveta, voltando para o salão.')
        EscolhaImpacto1.append('VOCÊ NÃO ABRIU A GAVETA, DEIXANDO A CHAVE PARA TRÁS')
        biblioteca()

def lampiao():
    sprint('Segui em direção ao velho lampião de ferro, com uma vela não muito gasta, amarelada e pouco derretida.')
    input('')
    os.system('cls')
    print(Fore.YELLOW + 'LARA')
    sprint('Pode ser uma boa levar.')
    input('')
    acao_biblioteca2 = input('Pegar o lampião?\n[1] - Sim\n[2] - Não\n>>> ')
    if acao_biblioteca2 == '1':
        os.system('cls')
        print(Fore.YELLOW + 'LARA')
        sprint('E se faça luz, não é mesmo?')
        input('')
        print(Style.BRIGHT + Back.WHITE + 'VOCÊ GANHOU LAMPIÃO DE LUZ!')
        Inventario.append('LAMPIÃO')
        EscolhaImpacto2.append('VOCÊ CONSEGUIU ALGO PARA ILUMINAR SEU CAMINHO!')
        input('')
        biblioteca_if_lampiao()
    elif acao_biblioteca2 == '2':
        os.system('cls')
        print(Fore.YELLOW + 'LARA')
        sprint('Não, melhor não tocar em nada.')
        EscolhaImpacto2('VOCÊ NÃO PEGOU O LAMPIÃO.')
        biblioteca()

def buraco():
    print(Fore.YELLOW + 'LARA')
    sprint('*suspiro*')
    input('')
    os.system('cls')
    print(Fore.YELLOW + 'LARA')
    sprint('Deus, por favor, que esteja lá.')
    input('')
    os.system('cls')
    sprint('A frente, descendo para o âmago da terra, só era possível ver a escuridão, como uma entrada para o fundo do abismo.')
    input('')
    if 'LAMPIÃO' in Inventario:
        print(Fore.YELLOW + 'LARA')
        sprint('Pera, a luz!')
        input('')
        os.system('cls')
        sprint('Peguei o lampião e fui até as velas acesas na parede, acendendo e voltando para a entrada do buraco. ')
        sprint('Descendo devagar com a luz, consegui ver os deslizes e quedas havia no buraco, seguindo com cautela pelo vão até o fundo.')
        input('')
        sprint('Ao longe, apesar do tempo que passei para descer por causa da cautela para não cair, consegui ver mais uma luz, uma iluminação fraca, mas visível cortando o vão de escuridão.')
        input()
        os.system('cls')
        print(Fore.YELLOW + 'LARA')
        sprint('Okay, calma...')
        EscolhaImpacto3.append('GRAÇAS A LUZ, VOCÊ NÃO SE MACHUCOU AO DESCER O BURACO')
        input()
        sprint('A descida até o vão foi so tornando menos ingríme conforme ia descendo, contudo mais quente.')
        sprint('Além do calor, uma leve fumaça seguia a saída do buraco, procurando ar livre onde se dissipar.')
        input('')
        os.system('cls')
        print(Fore.YELLOW + 'LARA')
        sprint('Okay, forças. Tem que estar aqui.')
        input()
        os.system('cls')
        sprint('Desci com cautela, avaliando os movimentos das sombras reveladas por aquela luz que se encontrava no fim daquele túnel.\nUm rugido, grunido, ou até um leve movimento era o suficiente para cortar aquele silêncio.')
        input()
        sprint('E era exatamente a última coisa que eu queria.')
        os.system('cls')
        sprint('Desci um pouco mais, agora me atentando a fonte de luz naquele buraco infernal, e o por que aquele calor nauseante.')
        cozinha()
    else:
        sprint('Desci no buraco devagar, calmamente caminhando em direção a escuridão que se prostava a frente.')
        sprint('O buraco parecia descer infinitamente, mergulhando mais na escuridão, abandonando a luz das velas atrás e convidando para um breu absurdo.')
        input('')
        os.system('cls')
        print(Fore.YELLOW + 'LARA')
        sprint('merda, merda, merda...')
        input('')
        os.system('cls')
        sprint('O chão era cada vez mais traçoeiro, mais escorregadio e mais ameaçador, como uma ameaça constante me convidando para cair.\nA escuridão também não parecia ajudar, onde um palmo a frente era próximo a invísivel.')
        input()
        os.system('cls')
        print(Fore.YELLOW + 'LARA')
        sprint('Okay, devagar...É só andar devagar... bem devag-')
        #Teste linha qte
        os.system('cls')
        print(Fore.RED + 'ANFITRIÃO')
        sprint('Olá.')
        sprint('Me desculpe atrapalhar seu jogo.')
        input()
        os.system('cls')
        print(Fore.RED + 'ANFITRIÃO')
        sprint('Só acho que deveria lhe instruir sobre algo.')
        input()
        os.system('cls')
        print(Fore.RED + 'ANFITRIÃO')
        sprint('Durante o jogo, você encontrará QTE (Quick Time Events) que irão decidir se terá sucesso ou não em sua empreitada.')
        input()
       
        os.system('cls')
        print(Fore.RED + 'ANFITRIÃO')
        sprint('Gostaria de dar um exemplo.')
        os.system('cls')
        qte_tutorial()
        if 'SUCESSO' in QTE_Tutorial:
            os.system('cls')
            print(Fore.RED + 'ANFITRIÃO')
            sprint('Parabéns, você está aprendendo muito bem!')
            input()
        else:
            os.system('cls')
            print(Fore.RED + 'ANFITRIÃO')
            sprint('Oh não, você não conseguiu a tempo...')
            input()
            sprint('Não há problema! Ainda existirão outras chances.')
            input()
        os.system('cls')
        print(Fore.RED + 'ANFITRIÃO')
        sprint('Deixarei você retornar a sua diversão agora.')
        sprint('Afinal, ainda há muito o que fazer.')
        input()
        os.system('cls')
        print(Fore.RED + 'ANFITRIÃO')
        sprint('Bom jogo.')
        input()
        os.system('cls')

        sprint('Como se pudesse me ouvir e fizesse chacota da minha absurda tentativa, escorreguei entre as reentrâncias do buraco.')
        qte_1()
        if 'SUCESSO' in QTE_1:
            sprint('Rapidamente, me agachando para recuperar meu equilíbrio, consegui me segurar nos vincos do chão da caverna.')
            input(Fore.YELLOW + 'LARA')
            sprint('Porra, essa foi por pouco...')
            input()
            EscolhaImpacto3.append('VOCÊ CONSEGUIU SE EQUILIBRAR E NÃO SE MACHUCOU NA DESCIDA.')
            os.system('cls')
            sprint('Desci calma e vagarosamente, agora atenta e mais cautelosa ao escorregadio buraco')
            sprint('E ao longe, uma fonte de luz alaranjada se encontrava.')
            input()
            sprint('Quando mais eu descia, mais quente ficava, como uma fornalha aberta ou uma sala trancada em pleno verão.')
            input()
            sprint('Ao chegar, consegui ver o que me esperava naquele calor infernal.')
            cozinha()
        else:
            sprint('Apenas fechei os olhos, enquanto sentia meu corpo rolar cada vez mais adentro, para o fundo do buraco.')
            input()
            os.system('')
            print(Fore.RED + 'LARA')
            sprint('Ai, meu deus...')
            input()
            os.system('cls')
            sprint('Senti assim que recuperei meus sentidos. Uma dor tangente ocupou meu corpo, que me forçou a engolir um gemido de dor profundo.')
            input()
            os.system('cls')
            print(Fore.YELLOW + 'LARA')
            sprint('Ai meu deus, não, aqui não.')
            input()
            os.system('cls')
            sprint('Feridas. Diversas escoriações pelo corpo.\nTudo que menos podia acontecer neste buraco infernal, menos isso. Que o pajé esteja certo e aquele monstro esteja bem longe daqui.')
            EscolhaImpacto3.append('VOCÊ CAIU, SE MACHUCANDO NA DESCIDA.')
            input()
            sprint('Me levantei calmamente, apoiando meus braços nas paredes cavernosas, que agora, dominadas por uma luz, revelavam a origem daquele calor infernal.')
            cozinha()

def cozinha():
    os.system('cls')
    sprint('Ao centro do salão, um caldeirão gigantesco se encontrava borbulhando, maturando uma sopa verde e que boiava as mais grotescas aberrações possíveis.')
    input()
    sprint('Tive que correr aos mãos ao meu nariz, tentando impedir aquele cheiro fétido de invadir minhas narinas.')
    input()
    os.system('cls')
    print(Fore.YELLOW + 'LARA')
    sprint('Meu deus, aquilo é...')
    input()
    os.system('cls')
    sprint('Entranhas.') 
    sprint('Diversas delas boiavam a superfície daquela água aborrenta. Intestinos, ossos, pulmões...humanos?')
    input()
    sprint('Tive que engolir a náusea que começava a borbulhar em minha garganta, ampliada por aquele fedor absurdo que sucateava o ar já insuficiente naquela sala')
    input()
    os.system('cls')
    print(Fore.YELLOW + 'LARA')
    sprint('Alí!')
    input()
    os.system('cls')
    sprint('Estantes de livros se encontravam ao redor de uma mesa de alquimia, onde haviam potes, especiarias secas, rascunhos e... uma adaga suja de sangue seco.')
    input()
    os.system('cls')
    print(Fore.YELLOW + 'LARA')
    sprint(f'Vai caramba, {"".join(Planta)}, por favor.')
    input()
    os.system('cls')
    sprint('Quanto mais livros eu abria, menos pareciam se relacionar a plantas. Alguns falavam sobre diversas plantas, mas nenhuma sobre a que o pajé mencionou.')
    sprint(f'Além disso, ele havia sido específico. Livro de couro com simbolo de {"".join(Signo)}, tiras velhas e manchadas, como um pergaminho antigo.')
    input()
    os.system('cls')
    print(Fore.YELLOW + 'LARA')
    sprint('Onde que ela guarda essa merd-')
    input()
    os.system('cls')
    sprint('Passos.')
    input()
    sprint('Discerníveis.')
    sprint('pesados e abafados, como se machucassem a terra que pisavam.')
    input()
    sprint('e vindo em direção a mim.')
    input()
    os.system('cls')
    print(Fore.YELLOW + 'LARA')
    sprint('-merda...')
    input()
    os.system('cls')
    cozinha_choice()

def cozinha_choice():
    print(Fore.YELLOW + 'LARA')
    sprint('(meu deus, ela está aqui!)')
    input()
    os.system('cls')
    sprint('Olhei ao redor rapidamente, a procura de algum lugar onde eu pudesse me esconder antes que aquilo chegasse.')
    input()
    os.system('cls')
    print(Fore.YELLOW + 'LARA')
    sprint('bingo.')
    input()
    os.system('cls')
    sprint('Ao canto da sala, próximo a uma estante, uma mesa coberta com um pano que um dia teve a coloração branca.')
    sprint('Entrei debaixo da mesa, agradeçendo ao pano ser de tão péssima qualidade que conseguia ver claramente a silhueta do caldeirão.')
    input()
    sprint('e dela.')
    input()
    os.system('cls')
    print(Fore.YELLOW + 'Lara')
    sprint('deus do céu...')
    input()
    os.system('cls')
    sprint('Ela era horrível.')
    input()
    sprint('Primeiro veio o cheiro. Achei que não poderia piorar o ar que já era quase impossível de respirar, claustrofôbico e pesado, que pesava os pulmões a cada lufada.')
    input()
    sprint('Mas o cheiro dela era horrível. Tive que tapar o nariz, para impedir aquele aroma podre de invadir meu corpo.\nSujeira, suor, bolor e morte.')
    input()
    os.system('cls')
    sprint('Ela foi se aproximando mais do caldeirão, e sua figura foi se tornando mais discernível.')
    sprint('Robusta, áspera e purulenta, sua pele, enrugada, decrépita e repleta de cicatrizes, auxiliava naquele nauseante cheiro de podre.\nSeu rosto, de aparência reptiliana, exibia dentes amarelados e serrilhados, porém afiados como adagas.')
    input()
    os.system('cls')
    sprint('O tempo pareceu andar devagar por um tempo, enquanto ela caminhava em direção ao borbulhante caldeirão. Sua figura era assustadora, mas hipnotizante.\nComo uma obra prima do pior que pode existir. O mal encarnado em pele de...seja lá o que ela seja.')
    input()
    if 'CHAVE VELHA' in Inventario:
        os.system('cls')
        print(Fore.GREEN + 'CUCA')
        sprint('Até quando vai ficar aí me olhando, garota burra?')
        input('')
        os.system('cls')
        sprint('O tempo parou e o silêncio dominou o ar. Nada além do barulho do caldeirão borbulhando.')
        input()
        sprint('e medo.')
        input()
        os.system('cls')
        print(Fore.GREEN + 'CUCA')
        sprint('Saia enquanto ainda tenho paciência.')
        input('')
        os.system('cls')
        sprint('merda, merda, merda.')
        sprint('Ela não se virou do caldeirão, apenas continuou mexendo com uma grande colher aquela mistura pútrida, espalhando mais o cheiro.')
        input()
        os.system('cls')
        sprint('Devagar, sai aos poucos debaixo da mesa, atenta a qualquer movimento brusco daquela...coisa, que pudesse significar perigo.')
        input()
        os.system('cls')
        print(Fore.YELLOW + 'LARA')
        sprint('Por favor, não me mate.')
        input()
        os.system('cls')
        sprint('Ela parou de mover a colher por um segundo e desviou o olhar do caldeirão, como se refletisse sobre a possibilidade.')
        input()
        os.system('cls')
        print(Fore.GREEN + 'CUCA')
        sprint('Diga, ratinho. O que faz na minha cozinha?')
        input()
        os.system('cls')
        sprint('Sua voz era ríspida e profunda, como um urro gutural de um abismo. Carregada de algo sombrio.')
        input()
        os.system('cls')
        print(Fore.YELLOW + 'LARA')
        sprint('O pajê me disse que-')
        os.system('cls')
        print(Fore.GREEN + 'CUCA')
        sprint('Aquele velho acha que pode fazer algo aqui?')
        input()
        os.system('cls')
        sprint('Sua aura era assustadora, e sua presença fazia meu corpo se enrijecer por inteiro, como se a qualquer momento, ela pudesse se teleportar até mim.')
        input()
        os.system('cls')
        print(Fore.YELLOW + 'LARA')
        sprint('Eu não...')
        input()
        os.system('cls')
        print(Fore.GREEN + 'CUCA')
        sprint('Recomendo que você diga o que quer logo, sua criatura nojenta. Já basta ter invadido minha casa, não me faça perder a paciência.')
        input()
        os.system('cls')
        sprint('Claro, o livro.')
        input()
        os.system('cls')
        print(Fore.YELLOW + 'LARA')
        sprint('O pajê me disse que você poderia me ajudar. A achar algo.')
        input()
        os.system('cls')
        print(Fore.GREEN + 'CUCA')
        sprint('Ele disse, não disse...')
        input()
        os.system('cls')
        sprint('O tempo pareceu andar devagar por um segundo, como se esperasse que alguém tivesse coragem de cortar o silêncio que existia, quebrado apenas pelo borbulhante som do caldeirão.')
        input()
        os.system('cls')
        print(Fore.GREEN + 'CUCA')
        sprint('O que eu ganho com isso, garota?')
        input()
        os.system('cls')
        print(Fore.YELLOW + 'LARA')
        sprint('O que você ganha?')
        print('[1] Meu sangue')
        if 'CHAVE VELHA' in Inventario:
            print('[2] Chave')
        cucatrade = input('>>>')
        if cucatrade == '1':
            os.system('cls')
            print(Fore.GREEN + 'CUCA')
            sprint('Hmmmm...')
            input()
            sprint('Talvez o que falta.')
            input()
            os.system('cls')
            sprint('Ela caminhou até a mesa de alquimia, pegando aquela adaga suja da mesa e vindo em minha direção.')
            input()
            os.system('cls')
            print(Fore.GREEN + 'CUCA')
            sprint('Sua mão.')
            input()
            os.system('cls')
            sprint('Relutante, estendi a mão para a criatura na minha frente, que a segurou com uma mão verrugosa e garras sujas e afiadas, me arrastando em direção ao caldeirão borbulhante.')
            input()
            os.system('cls')
            print(Fore.GREEN + 'CUCA')
            sprint('Não se mova.')
            input()
            os.system('cls')
            sprint('Engoli seco enquanto vi a adaga se aproximando da minha mão aos poucos.')
            input()
            os.system('cls')
            print(Fore.YELLOW + 'LARA')
            sprint('Vai doer?')
            input()
            os.system('cls')
            sprint('Ela abriu um sorriso maléfico, exaurindo seu hálito de morte e mostrando aqueles dentes serrilhados assustadores.')
            input()
            sprint('E de repente, uma dor lancinante se afundou em mim. Como um filete de brasa,a adaga cortou a palma da minha mão, enviando uma dorolosa e agonizante sensação.')
            sprint('Mordi os dentes, buscando forças para não desmaiar daquela dor horrível.')
            input()
            os.system('cls')
            print(Fore.GREEN + 'CUCA')
            sprint('Isso, sangre pra mim...')
            input()
            os.system('cls')
            sprint('Um rio de sangue seguia pela lámina da adaga até o cabo, gotejando no caldeirão e alterando sua cor.')
            input()
            os.system('cls')
            print(Fore.YELLOW + 'LARA')
            sprint('ME SOLTA!')
            input()
            os.system('cls')
            sprint('Puxei meu braço com toda a força possível, caindo ao chão com força. Tudo ao meu redor girava, e a sensação de dor e náusea estava me sugando as forças.')
            input()
            os.system('cls')
            print(Fore.GREEN + 'CUCA')
            sprint('Sim, isso. perfeito...')
            input()
            os.system('cls')
            sprint('Aquela monstruosidade estava apenas bebendo o conteúdo daquele caldeirão como uma besta, saboreando cada gota daquela obscenidade.')
            input()
            sprint(f'Quando notei, em sua cintura, preso a uma fivela, um livro. Não qualquer livro. O bendito livro. Com o simbolo de {"".join(Signo)} e as tiras desgastadas.')
            input()
            os.system('cls')
            print(Fore.YELLOW + 'LARA')
            sprint('(o que eu faço?)')
            bookchoice = input('[1] Pegar o livro.\n[2] Falar para a Cuca cumprir sua parte do acordo.\n>>> ')
            if bookchoice == '1':
                sprint('Ela estava totalmente distraída, o que poderia me possibilitar simplemente pegar o livro e cair o fora dalí.')
                input()
                sprint('Me levantei devagar, me aproximando aos poucos da criatura disforme que quase afundava sua cabeça no caldeirão.')
                sprint('Cautelosamente desprendi o livro da fivela da bruxa e fui me afastando aos poucos em direção ao buraco, pronta para sair em direção a floresta novamente.')
                Inventario.append('HERBÁRIO')
                input()
                os.system('cls')
                sprint('Assim que me afastei o suficiente para que ela não conseguisse me ouvir, comecei a correr, usando toda minha energia para fugir o mais rápido possível daquele lugar.')
                input()
                os.system('cls')
                print(Fore.YELLOW + 'LARA')
                sprint('Isso, vai Lara, você vai conseguir, você vai co-')
                input()
                os.system('cls')
                sprint('Não.')
                input()
                sprint('Não pode ser.')
                os.system('cls')
                sprint('Em frente ao que deveria ser a saída daquela árvore, uma enorme pedra havia se alojado no lugar, tapando toda e qualquer chance de sair.')
                input()
                os.system('cls')
                print(Fore.YELLOW + 'LARA')
                sprint('Não, não, não.')
                input()
                sprint('Tentei mover a pedra a todo custo, mas nem se mexia. Não havia nenhuma fresta onde eu pudesse passar, absolutamente nada. Era como se nunca tivesse sido aberto.')
                input()
                os.system('cls')
                print(Fore.GREEN + 'CUCA')
                sprint('LADRA!!!')
                input()
                os.system('cls')
                sprint('Um urro gutural saiu das profundidades e o som de uma criatura se aproximando muito rápido enchia meus ouvidos, enviando adrenalina para minhas pernas.')
                input()
                os.system('cls')
                print(Fore.YELLOW + 'LARA')
                sprint('Merda!')
                input()
                os.system('cls')
                sprint('Olhando ao redor, notei um buraco diferente na parede, um que não existia antes. Provavelmente o lugar onde aquele monstro estava.')
                print(Fore.GREEN + 'CUCA')
                sprint('NENHUM RATO FOGE DE MIM!')
                input()
                os.system('cls')
                print(Fore.YELLOW + 'LARA')
                sprint('Okay, Lara, corre!')
                input()
                os.system('cls') 
                fuga() 
            elif bookchoice == '2':
                    os.system('cls')
                    print(Fore.YELLOW + 'LARA')
                    sprint('Eu cumpri minha parte do acordo. Sua vez!')
                    input()
                    os.system('cls')
                    sprint('A fera apenas continuou bebendo do caldeirão. Sem tentar sequer olhar para mim.')
                    bookchoice2 = input('[1] Pegar o livro\n[2] Chamar a Cuca novamente\n>>> ')
                    if bookchoice2 == '1':
                        sprint('Sabe de uma? Foda-se.')
                        sprint('Me levantei devagar, me aproximando aos poucos da criatura disforme que quase afundava sua cabeça no caldeirão.')
                        sprint('Cautelosamente desprendi o livro da fivela da bruxa e fui me afastando aos poucos em direção ao buraco, pronta para sair em direção a floresta novamente.')
                        Inventario.append('HERBÁRIO')
                        input()
                        os.system('cls')
                        sprint('Assim que me afastei o suficiente para que ela não conseguisse me ouvir, comecei a correr, usando toda minha energia para fugir o mais rápido possível daquele lugar.')
                        input()
                        os.system('cls')
                        print(Fore.YELLOW + 'LARA')
                        sprint('Isso, vai Lara, você vai conseguir, você vai co-')
                        input()
                        os.system('cls')
                        sprint('Não.')
                        input()
                        sprint('Não pode ser.')
                        os.system('cls')
                        sprint('Em frente ao que deveria ser a saída daquela árvore, uma enorme pedra havia se alojado no lugar, tapando toda e qualquer chance de sair.')
                        input()
                        os.system('cls')
                        print(Fore.YELLOW + 'LARA')
                        sprint('Não, não, não.')
                        input()
                        sprint('Tentei mover a pedra a todo custo, mas nem se mexia. Não havia nenhuma fresta onde eu pudesse passar, absolutamente nada. Era como se nunca tivesse sido aberto.')
                        input()
                        os.system('cls')
                        print(Fore.GREEN + 'CUCA')
                        sprint('LADRA!!!')
                        input()
                        os.system('cls')
                        sprint('Um urro gutural saiu das profundidades e o som de uma criatura se aproximando muito rápido enchia meus ouvidos, enviando adrenalina para minhas pernas.')
                        input()
                        os.system('cls')
                        print(Fore.YELLOW + 'LARA')
                        sprint('Merda!')
                        input()
                        os.system('cls')
                        sprint('Olhando ao redor, notei um buraco diferente na parede, um que não existia antes. Provavelmente o lugar onde aquele monstro estava.')
                        print(Fore.GREEN + 'CUCA')
                        sprint('NENHUM RATO FOGE DE MIM!')
                        input()
                        os.system('cls')
                        print(Fore.YELLOW + 'LARA')
                        sprint('Okay, Lara, corre!')
                        input()
                        os.system('cls')
                        fuga()
                    elif bookchoice2 == '2':
                        os.system('cls')
                        print(Fore.YELLOW + 'LARA')
                        sprint('EI!')
                        input()
                        os.system('cls')
                        sprint('Ela parou de se mover alguns segundos, calmamente se afastando do caldeirão.')
                        input()
                        sprint('Contudo, quando se virou em minha direção, seu olhar era mais animalesco. Como um cão raivoso, as veias em seu olho amarelado estavam saltadas e arregalados, tomados por uma selvageri absurda.')
                        input()
                        os.system('cls')
                        print(Fore.GREEN + 'CUCA')
                        sprint('Você...é deliciosa...')
                        input()
                        os.system('cls')
                        sprint('Seu olhar foi se tornando mais lascivo, e o medo me engolfou completamente. Cada célula em meu corpo queria gritar e correr, mas aquela coisa ocupava grande parte da sala.')
                        input()
                        os.system('cls')
                        print(Fore.YELLOW + 'LARA')
                        sprint('Você me prometeu...')
                        input()
                        os.system('cls')
                        print(Fore.GREEN + 'CUCA')
                        sprint('eu...quero...')
                        input()
                        print(Fore.RED + 'MAIS')
                        input()
                        sprint('Ela avançou contra mim com velocidade absurda, com suas mãos estendidas em direção a meu pescoço.')
                        qte_2()
                        if 'SUCESSO' in QTE_2:
                            sprint('Rapidamente me arremessei para a direita, passando por debaixo de sua tentativa e enviando a cuca contra a mesa em minhas costas, destruindo a mesa.')
                            input()
                            sprint('Me levantei, pronta para fugir do buraco a qualquer movimento brusco dela. Mas ela estava imóvel.')
                            input()
                            os.system('cls')
                            print(Fore.YELLOW + 'LARA')
                            sprint('Okay...Respira, Lara...meu deus.')
                            input()
                            os.system('cls')
                            sprint('A adrenalina fazia o sangue bombear em meus ouvidos, me mantendo ligada para qualquer movimento em brusco daquela montanha.')
                            input()
                            sprint('Com cautela, fui me dirigindo em direção a ela, devagar e atenta a qualquer sinal de vida que ela pudesse manifestar.')
                            sprint('Desafivelei o livro dela e corri o mais rápido possível para longe dalí, escalando o buraco com o mais rápido que minha força me permitia.')
                            os.system('cls')
                            print(Fore.YELLOW + 'LARA')
                            sprint('Isso, vai Lara, você vai conseguir, você vai co-')
                            input()
                            os.system('cls')
                            sprint('Não.')
                            input()
                            sprint('Não pode ser.')
                            os.system('cls')
                            sprint('Em frente ao que deveria ser a saída daquela árvore, uma enorme pedra havia se alojado no lugar, tapando toda e qualquer chance de sair.')
                            input()
                            os.system('cls')
                            print(Fore.YELLOW + 'LARA')
                            sprint('Não, não, não.')
                            input()
                            sprint('Tentei mover a pedra a todo custo, mas nem se mexia. Não havia nenhuma fresta onde eu pudesse passar, absolutamente nada. Era como se nunca tivesse sido aberto.')
                            input()
                            os.system('cls')
                            print(Fore.GREEN + 'CUCA')
                            sprint('LADRA!!!')
                            input()
                            os.system('cls')
                            sprint('Um urro gutural saiu das profundidades e o som de uma criatura se aproximando muito rápido enchia meus ouvidos, enviando adrenalina para minhas pernas.')
                            input()
                            os.system('cls')
                            print(Fore.YELLOW + 'LARA')
                            sprint('Merda!')
                            input()
                            os.system('cls')
                            sprint('Olhando ao redor, notei um buraco diferente na parede, um que não existia antes. Provavelmente o lugar onde aquele monstro estava.')
                            print(Fore.GREEN + 'CUCA')
                            sprint('NENHUM RATO FOGE DE MIM!')
                            input()
                            os.system('cls')
                            print(Fore.YELLOW + 'LARA')
                            sprint('Okay, Lara, corre!')
                            input()
                            os.system('cls') 
                            fuga()
                        else:
                            sprint('Suas mãos se enrolaram ao redor do meu pescoço, apertando fortemente e cortando o ar dos meus pulmões.')
                            input()
                            sprint('Seu língua lambia os dentes afiados enquanto cada vez mais, eu mergulhava na escuridão.')
                            input('')
                            os.system('cls')
                            print(Fore.GREEN + 'CUCA')
                            sprint('Você será um belo troféu...')
                            os.system('cls')
                            print(Fore.RED + 'GAME OVER')
                            tryagain = input('[1] Checkpoint\n[2] Voltar ao menu\n>>> ')
                            if tryagain == '1':
                                QTE_2.clear
                                cozinha()
                            elif tryagain == '2':
                                sprint('ALERTA\nCaso vá ao menu, perderá TODO o progresso durante o jogo.\nTem certeza?')
                                areyousure = input('[1] SIM\n[2] NÃO\n>>> ')
                                if areyousure == '1':
                                    cleanup()
                                    menu()
                                elif areyousure == '2':
                                    sprint('Retornando ao checkpoint...')
                                    input('PRESSIONE ENTER PARA CONTINUAR...')
                                    os.system('cls')
                                    QTE_2.clear
                                    cozinha()
        elif cucatrade == '2':
                os.system('cls')
                sprint('Ela se virou de sobressalto, e seu olhos negros se tornaram mais furiosos.')
                input()
                os.system('cls')
                print(Fore.GREEN + 'CUCA')
                sprint('ONDE VOCÊ PEGOU ISSO, SUA LADRA?!')
                input()
                os.system('cls')
                sprint('Sua voz se tornou mais ameaçadora do que antes, mais agressiva, mais gutural. Como um cão furioso e cheio de ódio.')
                input()
                os.system('cls')
                print(Fore.YELLOW + 'LARA')
                sprint('Eu achei naquela mesa, eu-')
                os.system('cls')
                print(Fore.GREEN + 'CUCA')
                sprint('CALADA!')
                input()
                os.system('cls')
                sprint('Sua figura se enrijeceu por alguns segundos e pareceu ficar maior, como se todas as sombras do ambiente se unissem a ela.')
                input()
                print(Fore.GREEN + 'CUCA')
                sprint('Sabe o que fazemos com ratos na cozinha?')
                input()
                os.system('cls')
                sprint('Minha saliva desceu pesada em minha garganta, carregada de medo e desespero por seja lá o que ela queira fazer.')
                input()
                os.system('cls')
                print(Fore.YELLOW + 'LARA')
                sprint('...não?')
                input()
                sprint('Aquela figura monstruosa se virou devagar em minha direção, revelando seu rosto escamoso com mais detalhes.')
                sprint('Sua pele era áspera e purulenta, como escamas ressecadas e feridas infectadas. Mas o mais assustador eram seus olhos.')
                input()
                sprint('Negros. Sem nenhum reflexo. Profundos e escuros, pareciam duas órbitas negras sem vida. Eram frios, penetrantes e famintos.')
                input()
                os.system('cls')
                print(Fore.GREEN + 'CUCA')
                sprint('Nós envenenamos e jogamos fora.')
                input()
                os.system('cls')
                sprint('Cada pelo em meu corpo se arrepiou profundamente. Eu precisava de um plano. E urgente.')
                input()
                print(Fore.YELLOW + 'LARA')
                sprint('Você não-')
                input()
                os.system('cls')
                sprint('Antes que tivesse a chance de pensar, aquele monstro avançou contra mim, garras mirando em meu pescoço.')
                qte_6()
                if 'SUCESSO' in QTE_6:
                    sprint('Rapidamente me arremessei para a direita, passando por debaixo de sua tentativa e enviando a cuca contra a mesa em minhas costas, destruindo a mesa.')
                    input()
                    sprint('Me levantei, pronta para fugir do buraco a qualquer movimento brusco dela. Mas ela estava imóvel.')
                    input()
                    os.system('cls')
                    print(Fore.YELLOW + 'LARA')
                    sprint('Okay...Respira, Lara...meu deus.')
                    input()
                    os.system('cls')
                    sprint('A adrenalina fazia o sangue bombear em meus ouvidos, me mantendo ligada para qualquer movimento em brusco daquela montanha.')
                    input()
                    sprint('Com cautela, fui me dirigindo em direção a ela, devagar e atenta a qualquer sinal de vida que ela pudesse manifestar.')
                    sprint('Desafivelei o livro dela e corri o mais rápido possível para longe dalí, escalando o buraco com o mais rápido que minha força me permitia.')
                    os.system('cls')
                    print(Fore.YELLOW + 'LARA')
                    sprint('Isso, vai Lara, você vai conseguir, você vai co-')
                    input()
                    os.system('cls')
                    sprint('Não.')
                    input()
                    sprint('Não pode ser.')
                    os.system('cls')
                    sprint('Em frente ao que deveria ser a saída daquela árvore, uma enorme pedra havia se alojado no lugar, tapando toda e qualquer chance de sair.')
                    input()
                    os.system('cls')
                    print(Fore.YELLOW + 'LARA')
                    sprint('Não, não, não.')
                    input()
                    sprint('Tentei mover a pedra a todo custo, mas nem se mexia. Não havia nenhuma fresta onde eu pudesse passar, absolutamente nada. Era como se nunca tivesse sido aberto.')
                    input()
                    os.system('cls')
                    print(Fore.GREEN + 'CUCA')
                    sprint('LADRA!!!')
                    input()
                    os.system('cls')
                    sprint('Um urro gutural saiu das profundidades e o som de uma criatura se aproximando muito rápido enchia meus ouvidos, enviando adrenalina para minhas pernas.')
                    input()
                    os.system('cls')
                    print(Fore.YELLOW + 'LARA')
                    sprint('Merda!')
                    input()
                    os.system('cls')
                    sprint('Olhando ao redor, notei um buraco diferente na parede, um que não existia antes. Provavelmente o lugar onde aquele monstro estava.')
                    print(Fore.GREEN + 'CUCA')
                    sprint('NENHUM RATO FOGE DE MIM!')
                    input()
                    os.system('cls')
                    print(Fore.YELLOW + 'LARA')
                    sprint('Okay, Lara, corre!')
                    input()
                    os.system('cls') 
                    fuga()
                else:
                    sprint('Suas mãos se enrolaram ao redor do meu pescoço, apertando fortemente e cortando o ar dos meus pulmões.')
                    input()
                    sprint('Seu língua lambia os dentes afiados enquanto cada vez mais, eu mergulhava na escuridão.')
                    input('')
                    os.system('cls')
                    print(Fore.GREEN + 'CUCA')
                    sprint('Você será um belo troféu...')
                    os.system('cls')
                    print(Fore.RED + 'GAME OVER')
                    tryagain = input('[1] Checkpoint\n[2] Voltar ao menu\n>>> ')
                    if tryagain == '1':
                        QTE_6.clear
                        cozinha()
                    elif tryagain == '2':
                        sprint('ALERTA\nCaso vá ao menu, perderá todo o progresso durante o jogo.\nTem certeza?')
                        areyousure = input('[1] SIM\n[2] NÃO\n>>> ')
                        if areyousure == '1':
                            cleanup()
                            menu()
                        elif areyousure == '2':
                            QTE_6.clear
                            sprint('Retornando ao checkpoint...')
                            input('PRESSIONE ENTER PARA CONTINUAR...')
                            os.system('cls')
                            cozinha()
    else:
        os.system('cls')
        sprint('Ao prestar mais atenção, notei algo pendurado em uma fivela.') 
        sprint(f'Um livro. Não qualquer livro. O maldito livro com o símbolo de {"".join(Signo)} e as tiras desgastadas.')
        input()
        os.system('cls')
        print(Fore.YELLOW + 'LARA')
        sprint('(meu deus, como não tenho outra escolha, preciso do livro.)')
        input()
        os.system('cls')
        sprint('bem devagar, fui me aproximando, mantendo os pés chatos e fazendo o mínimo de barulho possível.')
        qte_3()
        if 'SUCESSO' in QTE_3:
            Inventario.append('HERBÁRIO')
            sprint('Isso!')
            input()
            sprint('Com o livro na mão, voltei abaixo da mesa, o segurando como se minha vida dependesse dele.')
            input()
            os.system('cls')
            print(Fore.YELLOW + 'LARA')
            sprint('(Okay, agora eu só preciso da oportunidade perfeita...)')
            input()
            os.system('cls')
            sprint('Antes que pudesse ter a chance de criar uma distração, ela seguiu em direção a mesa de alquimia, virando as costas para o buraco.')
            input()
            sprint('e me entregando a chance de fugir.')
            input()
            os.system('cls')
            sprint('Cheguei a entrada do buraco e comecei a escalar devagar, até estar na metade do buraco. A partir dalí, simplesmente comecei a correr o mais rápido possível, tentando me afastar desse lugar abominável.')
            input()
            sprint('Assim que cheguei ao salão principal, respirei de alívio, sendo capaz de respirar novamente.')
            input()
            os.system('cls')
            print(Fore.YELLOW + 'LARA')
            sprint('Agora eu só preciso cair o fora daqui.')
            input()
            os.system('cls')
            if 'LAMPIÃO' in Inventario:
                sprint('Quando me lembrei de algo. O lampião. Ainda estava comigo.')
                input()
                sprint('Peguei o objeto nas mãos, apreciando o castiçal interno segurado a chama. E óleo.')
                input()
                os.system('cls')
                print(Fore.YELLOW + 'LARA')
                sprint('(Eu posso acabar com isso...)')
                burntree = input('[1] Queimar árvore\n[2] Não queimar árvore\n>>> ')
                if burntree == '1':
                    Inventario.remove('LAMPIÃO')
                    EscolhaQueimarArvore.append('VOCÊ INCENDIOU A ÁRVORE, MATANDO A CRIANÇA PRESA.')
                    os.system('cls')
                    sprint('Chega. Chega dessa coisa aqui.')
                    input()
                    sprint('Fui até as velas novamente, acendendo o lampião e seguindo para a entrada da biblioteca.')
                    input()
                    os.system('cls')
                    print(Fore.YELLOW + 'LARA')
                    sprint('Queima no inferno, sua desgraçada.')
                    input()
                    os.system('cls')
                    sprint('Arremessei o lampião com toda a força possível, que se quebrou ao atingir uma das estantes de livros, automaticamente espalhando chamas e óleo por todos os lados.')
                    sprint('A madeira podre e decrépita só ajudou a engolfar tudo em chamas, enquanto eu corria para fora daquele pesadelo.')
                    input()
                    os.system('cls')
                    sprint('Ao chegar novamente a segurança da floresta, parei um pouco, apoiando as mãos nos joelhos e respirando ofegante, assistindo as chamas engolfarem a antiga árvore.')
                    input()
                    print(Fore.YELLOW + 'LARA')
                    sprint('Isso...acabou...')
                    input()
                    os.system('cls')
                    sprint('Me coloquei ereta novamente, segurando o livro em minhas mãos e apreciando a capa detalhada.')
                    input()
                    os.system('cls')
                    print(Fore.YELLOW + 'LARA')
                    sprint('Tô indo, Luna. Aguenta mais um pouco.')
                    input()
                    os.system('cls')
                    sprint('E com isso, abandonei aquele lugar, seguindo em direção a vila novamente.')
                    input()
                    outroAnfitrião()
                else:
                    sprint('Não.')
                    input()
                    sprint('Isso pode queimar toda uma floresta. Pensa, Lara.')
                    input()
                    os.system('cls')
                    sprint('Abandonei a ideia, seguindo para fora da árvore o mais rápido possível.')
                    input()
                    os.system('cls')
                    sprint('Ao chegar novamente a segurança da floresta, parei um pouco, apoiando as mãos nos joelhos e respirando ofegante, assistindo a antiga árvore, como uma entrada de um pesadelo..')
                    input()
                    print(Fore.YELLOW + 'LARA')
                    sprint('Isso...acabou...')
                    input()
                    os.system('cls')
                    sprint('Me coloquei ereta novamente, segurando o livro em minhas mãos e apreciando a capa detalhada.')
                    input()
                    os.system('cls')
                    print(Fore.YELLOW + 'LARA')
                    sprint('Tô indo, Luna. Aguenta mais um pouco.')
                    input()
                    os.system('cls')
                    sprint('E com isso, abandonei aquele lugar, seguindo em direção a vila novamente.')
                    input()
                    outroAnfitrião()
            else:
                sprint('Corri o mais rápido que pude para fora dalí, vendo a luz do dia se abrindo novamente, como acordar de um pesadelo.')
                input()
                sprint('Ao chegar novamente a segurança da floresta, parei um pouco, apoiando as mãos nos joelhos e respirando ofegante, assistindo a antiga árvore.')
                input()
                print(Fore.YELLOW + 'LARA')
                sprint('Isso...acabou...')
                input()
                os.system('cls')
                sprint('Me coloquei ereta novamente, segurando o livro em minhas mãos e apreciando a capa detalhada.')
                input()
                os.system('cls')
                print(Fore.YELLOW + 'LARA')
                sprint('Tô indo, Luna. Aguenta mais um pouco.')
                input()
                os.system('cls')
                sprint('E com isso, abandonei aquele lugar, seguindo em direção a vila novamente.')
                input()
                outroAnfitrião()
        else:
            sprint('creck')
            input()
            sprint('Um barulho, tão baixo mas tão alto, ressou pela sala. Um graveto, quebrado em meus pés.')
            input()
            os.system('cls')
            sprint('Devagar olhei para cima, em direção aos olhos negros que agora me encaravam de perto. Uma sensação de horror preencheu meu corpo, como um frio de inverno penentrando a espinha.')
            input()
            print(Fore.GREEN + 'CUCA')
            sprint('Parece que serei bem servida hoje...')
            input()
            os.system('cls')
            print(Fore.RED + 'GAME OVER')
            tryagain = input('[1] Checkpoint\n[2] Voltar ao menu\n>>> ')
            if tryagain == '1':
                cozinha()
            elif tryagain == '2':
                sprint('ALERTA\nCaso vá ao menu, perderá todo o progresso durante o jogo.\nTem certeza?')
                areyousure = input('[1] SIM\n[2] NÃO\n>>> ')
                if areyousure == '1':
                    cleanup()
                    menu()
                elif areyousure == '2':
                    QTE_3.clear
                    sprint('Retornando ao checkpoint...')
                    input('PRESSIONE ENTER PARA CONTINUAR...')
                    os.system('cls')
                    cozinha()

def fuga():
    sprint('Corri em direção a nova entrada, me encontrando com um espiral de raizes que seguia para o topo da árvore.')
    input()
    print(Fore.GREEN + 'CUCA')
    sprint('LADRA!')
    input()
    os.system('cls')
    sprint('Aquele monstro se aproximava cada vez mais de mim, reduzindo a distância a cada urro de ódio que gritava.')
    sprint('Comecei a correr em direção ao espiral, tentando estabelecer o maior nível de distância possível entre nos')
    input()
    os.system('cls')
    sprint('Subi as escadas em espirais o mais rápido que conseguia, sentindo meus pulmões queimarem.')
    input()
    os.system('cls')
    print(Fore.GREEN + 'CUCA')
    sprint('Você está em meu domínio, garota burra...')
    input()
    sprint('quem manda aqui...')
    input()
    sprint('SOU EU!')
    input()
    os.system('cls')
    sprint('Como se a árvore a pudesse ouvir, as raizes que serviam como escadas para os espirais começaram a se mover, retorcedo galhos e madeira.')
    input()
    os.system('cls')
    print(Fore.YELLOW + 'LARA')
    sprint('merda!')
    input()
    os.system('cls')
    sprint('Uma das raizes se retorceu em meu pé, me fazendo perder o equilíbrio.')
    qte_4()
    if 'SUCESSO' in QTE_4:
        print('')
        sprint('Consegui recuperar o equilíbrio a tempo, voltando a subir o mais rápido possível para o topo da árvore, desviando e saltando entre raizes.')
        input()
        os.system('cls')
        print(Fore.YELLOW + 'LARA')
        sprint('Corre Lara, corre!')
        input()
        os.system('cls')
        print(Fore.GREEN + 'CUCA')
        sprint('SIM, CORRA. CORRA O QUANTO QUISER.')
        input()
        os.system('cls')
        sprint('Minhas pernas doiam a cada salto e meu pulmão ardia, mais eu me recusava a parar. Ela estava em meu encalço, se guiando pelas raizes como se conhecesse cada movimento.')
        input()
        sprint('Contudo, ao longe, vi. Uma porta. Não tão pútrida como todas as outras. Mais nova, porém qum pouco apagada graças a cor da madeira. Era minha chance.')
        input()
        os.system('cls')
        sprint('Parei um segundo para sentir o momentum e corri, sentindo meus pulmões perderem força. Era um longo salto, mas um que eu teria que acertar.')
        input()
        os.system('cls')
        print(Fore.YELLOW + 'LARA')
        sprint('vai,vai,vai,vai, VAI!')
        input()
        qte_5()
        if 'SUCESSO' in QTE_5:
            sprint('Senti o impacto dos meus pés no chão com força, ardendo meus calcanhares.')
            input()
            os.system('cls')
            print(Fore.YELLOW + 'LARA')
            sprint('ISSO!')
            input()
            os.system('cls')
            sprint('Corri o mais rápido que pude até a porta, arrombando-a com um empurrão.')
            input()
            print(Fore.GREEN + 'CUCA')
            sprint('VOLTE AQUI, SUA RATA DESGRAÇ-    ')
            os.system('cls')
            sprint('Bati a droga da porta, prendendo-a com um tipo de pedaço enorme de madeira que havia ao lado, como uma tranca manual.')
            sprint('Não satisfeita, puxei um dos armários ao lado em cima da porta e me afastei, sentando ao chão para recuperar o fôlego.')
            input()
            os.system('cls')
            sprint('As lufadas de ar ardiam meus pitos conforme a adrenalina ia e diminuindo, me fazendo ficar cada vez mais tonta.')
            sprint('Conseguia sentir o sangue pulsar em minhas orelhas, e a náusea se acumulando em meu estômago.')
            input()
            os.system('cls')
            print(Fore.YELLOW + 'LARA')
            sprint('Respirar...devagar...')
            input()
            açougue()
        else:
            sprint('não.')
            input('')
            sprint('Senti meus pés escorregarem antes que pudesse tocar o chão da porta e não tive onde me segurar.')
            sprint('Senti o vento cortar o ar nas minhas costas por alguns poucos segundos.')
            input()
            sprint('E senti um último impacto, antes de tudo ficar escuro.')
            input()
            os.system('cls')
            print(Fore.RED + 'GAME OVER')
            tryagain = input('[1] Checkpoint\n[2] Voltar ao menu\n>>> ')
            if tryagain == '1':
                QTE_4.clear
                QTE_5.clear
                fuga()
            elif tryagain == '2':
                sprint('ALERTA\nCaso vá ao menu, perderá todo o progresso durante o jogo.\nTem certeza?')
                areyousure = input('[1] SIM\n[2] NÃO\n>>> ')
                if areyousure == '1':
                    cleanup()
                    menu()
                elif areyousure == '2':
                    QTE_4.clear
                    QTE_5.clear
                    sprint('Retornando ao checkpoint...')
                    input('PRESSIONE ENTER PARA CONTINUAR...')
                    os.system('cls')
                    fuga()

    else:
        print('')
        sprint('Errei o passo e senti meu corpo se desequilibrar totalmente, caindo diretamente de cara no chão. Senti meu nariz sangrar e a tortura da dor encher minha cabeça.')
        input()
        os.system('cls')
        sprint('E me lembro de apenas sentir sua sombra em cima de mim...')
        input()
        os.system('cls')
        print(Fore.RED + 'GAME OVER')
        tryagain = input('[1] Checkpoint\n[2] Voltar ao menu\n>>> ')
        if tryagain == '1':
            QTE_4.clear
            fuga()
        elif tryagain == '2':
            sprint('ALERTA\nCaso vá ao menu, perderá todo o progresso durante o jogo.\nTem certeza?')
            areyousure = input('[1] SIM\n[2] NÃO\n>>> ')
            if areyousure == '1':
                cleanup()
                menu()
            elif areyousure == '2':
                QTE_4.clear
                sprint('Retornando ao checkpoint...')
                input('PRESSIONE ENTER PARA CONTINUAR...')
                os.system('cls')
                fuga()

def açougue():
    os.system('cls')
    sprint('Conforme fui recuperando meu sentidos, olhei ao redor.')
    input()
    sprint('Apesar de escuro, era possível ver graças a algumas gotas de brilho do sol que passavam pelas dobras da madeira.')
    input()
    os.system('cls')
    sprint('O som das correntes, que pendiam enferrujadas pelos lugares, acompanhava um cheiro de ferrugem velha e umidade.')
    sprint('E ao redor de tudo, pequenas gaiolas. Acumuladas em torno de todo o ambiente.')
    input()
    os.system('cls')
    print(Fore.RED + 'BLAM')
    input()
    os.system('cls')
    sprint('O barulho daquele monstro tentando abrir a porta a força me ligou os sentidos, levantando e me preparando para fugir para qualquer lugar possível.')
    input()
    os.system('cls')
    print(Fore.YELLOW + 'LARA')
    sprint('Uma saída, uma saída...ali!')
    input()
    os.system('cls')
    sprint('Ao final da sala, as reentrancias da árvore se abriam, revelando a luz do sol e um buraco grande o suficiente para que eu pudesse passar.')
    input()
    sprint('Uma alegria descomunal tomou conta do meu corpo, e segui em direção a saída daquele pesadelo, ansiosa para respirar ar puro novamente.')
    input()
    os.system('cls')
    sprint('Até sentir.')
    input()
    sprint('Algo se segurou a meu calcanhar, enviando arrepios contra todo o meu corpo. Era frio, pequeno e frágil, como se um cadáver tocasse meus pés.')
    input()
    os.system('cls')
    sprint('Me virei aos poucos, pronta para encarar qualquer horror que estivesse a me tocar.')
    input()
    sprint('Mas o que me deparei, dobrou meu estômago.')
    input()
    os.system('cls')
    print(Fore.CYAN + 'CRIANÇA')
    sprint('Por favor, me ajuda...')
    input()
    os.system('cls')
    sprint('Em uma das gaiolas, pequena demais para sua estatura, o que o forçava a ficar sempre sentado, uma criança. Magra, como se não visse comida a decadas')
    sprint('Seus olhos estavam profundos e sua pele, repleta de arranhões, cortes e...marcas de dentes e garras.')
    sprint('Cicatrizes que devem ter se cicatrizado e se curado novamente.')
    input()
    os.system('cls')
    print(Fore.YELLOW + 'LARA')
    sprint('Meu deus...')
    input()
    os.system('cls')
    sprint('Lágrimas encheram meus olhos e a angústia me atingiu como um soco no estômago.')
    input()
    print(Fore.CYAN + 'CRIANÇA')
    sprint('Moça, me tira daqui, por favor...')
    input()
    os.system('cls')
    print(Fore.YELLOW + 'LARA')
    sprint('Eu...')
    input()
    print(Fore.RED + 'BLAM')
    input()
    os.system('cls')
    sprint('O barulho do monstro tentando derrubar a porta me deixou alerta novamente, me lembrando do porque eu estava presa ali.')
    input()
    sprint('Agachei perto da gaiola, notando um cadeado velho, mas robusto. Tentei a todo custo puxa-lo, mas a resistência daquele metal não parecia disposta a se dobrar.')
    input()
    os.system('cls')
    print(Fore.YELLOW + 'LARA')
    sprint('Merda!')
    input()
    os.system('cls')
    sprint('Não adiantava quando força eu fizesse, o cadeado ou as barras não cediam.')
    input()
    sprint('Olhei novamente para aquela pobre criança, seus olhos inchados de lágrimas e dos horrores que deve ter passado.')
    input()
    if 'CHAVE VELHA' in Inventario:
        os.system('cls')
        EscolhaCriançaSalva.append('VOCÊ USOU A CHAVE VELHA PARA ABRIR A GAIOLA, SALVANDO A CRIANÇA DA CUCA')
        print(Fore.YELLOW + 'LARA')
        sprint('Calma aí...')
        input()
        os.system('cls')
        sprint('Escavando meus bolsos, me lembrei da existência da chave que havia encontrado na biblioteca.')
        input()
        print(Fore.YELLOW + 'LARA')
        sprint('Vai, funciona...')
        input()
        os.system('cls')
        sprint('Coloquei a chave no cadeado, que se encaixou perfeitamente.')
        input()
        print(Fore.YELLOW + 'LARA')
        sprint('Isso!')
        input()
        os.system('cls')
        sprint('Girei a tranca da chave, abrindo sua fechadura e liberando a criança de dentro da gaiola, que assim que saiu, me abraçou fortemente.')
        sprint('Seu corpo, frágil e raquitico, era penoso a vista.')
        input()
        sprint('Com a pouca força que havia nela, ela apenas me segurava com força e soluçava de chorar.')
        input()
        os.system('cls')
        print(Fore.RED + 'BLAM')
        input()
        sprint('A criatura continuava tentando arrombar a porta, que cada vez mais cedia a força que era empunhada nela.')
        input()
        sprint('Segurei o rosto da criança em minhas mãos, olhando em seu olho.')
        input()
        os.system('cls')
        print(Fore.YELLOW + 'LARA')
        sprint('Escuta, a gente tem que sair daqui. Consegue correr?')
        input()
        os.system('cls')
        print(Fore.CYAN + 'CRIANÇA')
        sprint('acho que sim...')
        os.system('cls')
        input()
        print(Fore.YELLOW + 'LARA')
        sprint('Ótimo.')
        input()
        os.system('cls')
        sprint('Agarrei as mãos da criança e corri em direção ao buraco da árvore, ajudando ela a escalar e me deparando com uma visão direta da floresta.')
        input()
        sprint('Havia, em sua direita, através de raizes bruscas e mal organizadas, uma descida até outras árvores próximas.')
        input()
        os.system('cls')
        sprint('Descemos o mais rápido que conseguiamos até uma árvore mais próxima, que iam se interconectando, criando um caminho conturbado até o chão.')
        input()
        sprint('Ao longe, consegui ouvir o barulho da porta ceder, e um urro de ódio e fúria engolfar toda a floresta, como se o chão tremesse.')
        input()
        os.system('cls')
        sprint('Quando chegamos ao chão, não paramos para respirar um segundo, seguindo em direção ao além da floresta, fugindo para o mais longe daquele inferno possível.')
        input()
        outroAnfitrião()
    else:
        os.system('cls')
        EscolhaCriançaSalva.append('VOCÊ NÃO TINHA A CHAVE VELHA E NÃO FOI CAPAZ DE ABRIR A GAIOLA, DEIXANDO A CRIANÇA PARA TRÁS.')
        print(Fore.RED + 'BLAM')
        input()
        sprint('mas que merda...')
        input()
        os.system('cls')
        print(Fore.YELLOW + 'LARA')
        sprint('Me desculpa...')
        input()
        os.system('cls')
        print(Fore.CYAN + 'CRIANÇA')
        sprint('NÃO, ME TIRA DAQUI!')
        input()
        os.system('cls')
        sprint('Corri para a saída da árvore, enquanto os barulhos da porta e os gritos da criança pedindo por socorro ainda arrebatavam o ar, quase me levando a loucura.')
        input()
        sprint('Do lado de fora, uma descida de raizes retorcidas criava um caminho mal formado pela floresta, que se despejava em outras árvores, criando uma saída daquele pesadelo.')
        input()
        os.system('cls')
        sprint('Olhei novamente para trás, para a porta quase arrebentando e a criança com o olhar engolfado em desespero.')
        input()
        print(Fore.CYAN + 'CRIANÇA')
        sprint('não me deixa aqui...')
        input()
        os.system('cls')
        sprint('Me desculpa.')
        input()
        sprint('Desci as raizes o mais rápido que consegui, com a cacofonia dos gritos de desespero da criança e o urro monstruoso de uma criatura feroz')
        input()
        os.system('cls')
        sprint('Segurei o livro nos braços, sentindo a força em meu corpo se revigorar.')
        input()
        print(Fore.YELLOW + 'LARA')
        sprint('Tô indo, Luna. Aguenta firme.')
        input()
        os.system('cls')
        sprint('E segui para a floresta, para bem longe daquele pesadelo.')
        input()
        outroAnfitrião()

def outroAnfitrião():
    os.system('cls')
    print(Fore.RED + 'ANFITRIÃO')
    sprint('Foi uma aventura estonteante, não?')
    print('Assumo que tenha se divertido.')
    ending1 = input('[1] - Foi horrível...\n[2] - Foi maravilhoso!')
    if ending1 == '1':
        os.system('cls')
        print(Fore.RED + 'ANFITRIÃO')
        sprint('Ah...')
        input()
        sprint('Fico triste que tenha achado.')
        input()
        os.system('cls')
        print(Fore.RED + 'ANFITRIÃO')
        sprint('Temos uma surpresa agora.')
        input()
        os.system('cls')
        print(Fore.RED + 'ANFITRIÃO')
        sprint('Haverá uma nova opção agora. Escolhas.')
        input()
        sprint('Elas irão mostrar o que você fez durante a aventura.')
        input()
        os.system('cls')
        print(Fore.RED + 'ANFITRIÃO')
        sprint(f'Foi um prazer, {"".join(User)}.')
        input()
        os.system('cls')
        ssprint('Até breve...')
        input()
        os.system('cls')
        new_menu()
    elif ending1 == '2':
        os.system('cls')
        print(Fore.RED + 'ANFITRIÃO')
        sprint('Esplendido!')
        input()
        sprint('Foi sim uma aventura estoenteante.')
        input()
        os.system('cls')
        print(Fore.RED + 'ANFITRIÃO')
        sprint('Temos uma surpresa agora.')
        input()
        os.system('cls')
        print(Fore.RED + 'ANFITRIÃO')
        sprint('Haverá uma nova opção agora. Escolhas.')
        input()
        sprint('Elas irão mostrar o que você fez durante a aventura.')
        input()
        os.system('cls')
        print(Fore.RED + 'ANFITRIÃO')
        sprint(f'Foi um prazer, {"".join(User)}.')
        input()
        os.system('cls')
        ssprint('Até breve...')
        input()
        os.system('cls')
        new_menu()

#Jogo
menu()